### PR TITLE
Update requirements.txt to include cellpose

### PR DESCRIPTION
**Pull request by hinerm**

### CODE REVIEW

**Comment by hinerm** [comment]
@bethac07 @alicelucas this was necessary because without `cellpose` installed, other `CellProfiler-plugins` break (i.e. `RunImageJScript`) because the `runcellpose.py` setup fails.

**Comment by bethac07** [comment]
Hmmm, each plugin should be independent in its loading,  and I can't confirm either on my system - I had both modules importable, pip uninstalled cellpose, and it stopped loading in but RunImageJ did not...

image

**Comment by hinerm** [comment]
@bethac07 thanks for looking at it. I was getting runtime errors from pyimagej that seemed to go away after installing cellpose, but I can't reproduce either now so maybe it was a RunImageJScript configuration issue. Sorry for the distraction!

**Comment by ErinWeisbart** [comment]
Closing this PR because we are currently overhauling how we handle dependencies
(FYI @callum-jpg, in case this helps you)

**Pull request closed without merging**
