### PR TITLE
Update RunIJScript

### PR DESCRIPTION
**Pull request by hinerm**
This patch includes:
* Support for ij.ImagePlus script inputs/outputs
* Support for subclasses of net.imagej.Dataset and net.imagej.ImgPlus
* Automatic type conversion between CP and IJ, with a setting to disable if desired

### CODE REVIEW

**Review by bethac07 — CHANGES_REQUESTED** [review]
Thanks, great that you were able to get to this so quickly!

One thing I somehow didn't catch before is that your module doesn't seem to have a `variable_revision_number` ([example](https://github.com/CellProfiler/CellProfiler/blob/master/cellprofiler/modules/enhanceedges.py#L56)) - it's super important to have one so that you can have an `upgrade_settings` ([example](https://github.com/CellProfiler/CellProfiler/blob/master/cellprofiler/modules/enhanceedges.py#L373) ) so that CellProfiler knows how to open a pipeline saved with the OLD version of your module that now has new settings. As currently written, your new setting is added after the 8th setting in the `settings` list, so the functional part of your upgrade_settings would look something like `settings= settings[:8]+True+settings[8:]` (assuming, of course, you want the default value for people who are upgrading from v1 of the module to be True; ordinarily I would say it should be False, because when adding a new setting we typically say when pipelines are upgraded the new setting should be set to the least-perturbative-behavior, but a) we're in the plugins so we don't have to follow rules if we don't want to b) this is going to be a good change for the vast majority of folks and c) I don't think too many people are using this yet, and the ones who are, are savvy enough to figure out how to cope with the change.

One other super small change -can we change `Run ImageJ Script` in a couple of places to `RunImageJScript`, just to stylistically match other CellProfiler modules?

**Comment by hinerm** [comment]
@bethac07 :+1: thank you for the quick feedback!

>One thing I somehow didn't catch before is that your module doesn't seem to have a variable_revision_number

Makes total sense. I added an `upgrade_settings` implementation and it seems to work as intended.

>One other super small change -can we change Run ImageJ Script in a couple of places to RunImageJScript

100% of course. I think I got all these.

Let me know if you think of anything else!

**Comment by alicelucas** [comment]
Just chiming in here to confirm that the updated module still works on my end, AND the output image from our script now looks great :) Thanks Mark! 🎉

**Review by bethac07 — APPROVED** [review]

**Comment by bethac07** [comment]
LGTM! Thanks!

**Pull request merged**
